services:
  db:
    environment:
      POSTGRES_DB: pgg_auth_test
      POSTGRES_USER: pgg_auth_test
      POSTGRES_PASSWORD: pgg_auth_test
    ports:
      - "127.0.0.1:55439:5432"
    volumes:
      - postgres-auth-test-data:/var/lib/postgresql/data

volumes:
  postgres-auth-test-data:
